version: 1.0.{build}

environment:
  COVERALLS_REPO_TOKEN:
    secure: 2s5b3QG0J9qey9fgGMTtVP/AFWh2RH3FOm82ybS/MLHSjHwUgKw3h64//8ZUmf4+

assembly_info:
  patch: true
  file: AssemblyInfo.*
  assembly_version: "{version}"
  assembly_file_version: "{version}"
  assembly_informational_version: "{version}"

configuration: Release

build:
  project: Nancy.RestModule.sln

before_build:
  - nuget restore

after_test:
   - ps: .\nuget\pack.ps1
   - cmd: .\post_build.cmd

artifacts:
  - path: Nancy.RestModule\bin\Release\Nancy.RestModule.dll
    name: Nancy.RestModule.dll
  - path: '**\Nancy.RestModule.*.nupkg'

#uncomment to publish to NuGet
#deploy:
#  provider: NuGet
#  api_key:
#    secure: U9STqjDjIz1j/0PFSPM0sCYt+0WTU3Cx5w1cw06RWIdPeXZUmCq2nScvhimnQ9NH
#  artifact: /.*\.nupkg/