version: 1.0.{build}

#uncomment if tests are added
#environment:
#  COVERALLS_REPO_TOKEN:
#    secure: pmCqwxeGUuuRtSI8dRASV4pSiEluhcXR3xwFkYNnIfzStFtj7/4UQ4BbR9FxNHtf

assembly_info:
  patch: true
  file: AssemblyInfo.*
  assembly_version: "{version}"
  assembly_file_version: "{version}"
  assembly_informational_version: "{version}"

configuration: Release

build:
  project: Nancy.RestModule.sln

before_build:
  - nuget restore

after_test:
   - ps: .\nuget\pack.ps1

#uncomment if tests are added
#   - cmd: .\post_build.cmd

artifacts:
  - path: Nancy.RestModule\bin\Release\Nancy.RestModule.dll
    name: Nancy.RestModule.dll
  - path: '**\Nancy.RestModule.*.nupkg'

#uncomment to publish to NuGet
deploy:
  provider: NuGet
  api_key:
    secure: U9STqjDjIz1j/0PFSPM0sCYt+0WTU3Cx5w1cw06RWIdPeXZUmCq2nScvhimnQ9NH
  artifact: /.*\.nupkg/